Adding areas 85 introduced with 2.4 patch
Michaelangel007/d2_cheat_sheet pull request #37
Opened 2022-04-24 13:08 UTC by Wyrda65

Adding new areas 85 introduced in patch 2.4
Immunities data is taken from https://www.reddit.com/r/Diablo/comments/s9w26y/overview_of_immunities_in_the_new_level_85_zones/
Mob count is taken from older D2 level configuration file https://github.com/fabd/diablo2/blob/17d60a1085151a640b164e047b4e0afb179af254/code/d2_113_data/Levels.txt, which might be changed. Indeed few areas had more packs when hence updated accordingly

2022-04-24 14:35 UTC, Wyrda65 commented
I've also added Set Upping

2022-05-10 12:24 UTC, JSterling8 requested changes
Stony Tomb Level 1 and Level 2 are now level 85 areas but are still listed as level 78/79 in the area list at the bottom of the page around line #5950 or so.

2022-05-10 12:24 UTC, JSterling8 commented on index.html
> +    <tr><td                      ></td><td class='tooltip g22'>  Arachnid Lair         21  50  <span class='alvl83'>85</span> <span class='l'>    </span     ><span class='c'  >        </span   ><span
`alvl83` should be `alvl85`

2022-05-11 19:46 UTC, Wyrda65 commented on index.html
> +    <tr><td                      ></td><td class='tooltip g22'>  Arachnid Lair         21  50  <span class='alvl83'>85</span> <span class='l'>    </span     ><span class='c'  >        </span   ><span
fixed

2022-05-12 17:07 UTC, merged

2022-05-12 17:07 UTC, Michaelangel007 commented
Looks good.  Thanks for the patch!